### ISSUE TITLE
Property "userChatId" is not a valid property

### ISSUE THREAD

**Issue by neographikal** [SenTzu01/pimatic-telegram#6]
After updating to the latest version 1.1.2 I'm getting this notice in the logs and when I try to save the config in the GUI:

error [pimatic]: Invalid config of pimatic-telegram: Property "userChatId" is not a valid property

```
{
      "plugin": "telegram",
      "active": true,
      "host": "api.telegram.org",
      "apiToken": "xxx:xxxx-GUqgIc_JLAA",
      "userChatId": "xxxx",
      "recipients": [
        {
          "name": "@neographikal",
          "userChatId": "xxxx",
          "enabled": true,
          "admin": true
        }
      ]
    },
```

It's the userchatid in the upper part that's causing it, a remnant of the previous version. It would be nice if this breaking change in the config didn't break functionality. :)

**Comment by SenTzu01** [comment]
If the main userChatId (under apiToken) is the same as recipients.userChatId (the one directly under @neographical), you can safely remove the main userChatId in your config.json.
Else create a new user in your config.json with the same spec as @neographikal, but with the main userChatId and another name; then remove the main userChatId
This is a residual setting which is no longer used for the past few versions. It seems an old bug in the migration logic has been reintroduced due to branch merging in the past, will be fixed upstream.

**Comment by SenTzu01** [comment]
Bug fixed, will be in the next release

**Comment by neographikal** [comment]
cool, I suspected the migration logic, nice that it fixed :) Great plugin btw, I use it for alerting and stuff like that, lovely.

**Comment by SenTzu01** [comment]
Great to hear from a happy customer :)

Also do not forget to update your rules as the syntaxt is no longer downwards compatible !

See README.md

**Comment by neographikal** [comment]
And thanks for the time you are investing :)
